### PR TITLE
Added support for controlling DEBUG flag from env

### PR DESCRIPTION
**Pull request by vaibh27**
## Description

Added support to control DEBUG flag value from env file.

## Checklist

- [x] My submission is formatted according to the guidelines in the [contributing guide](/CONTRIBUTING.md)
- [x] My submission has a useful description
- [x] Code follows the established [CODE_OF_CONDUCT](https://github.com/Exifly/ApiVault/blob/main/CODE_OF_CONDUCT.md) guidelines.
- [x] Code has been tested thoroughly.
- [x] All commit messages are descriptive and follow the established commit message format.
- [ ] I have searched the repository for any relevant issues or pull requests
- [ ] Pull request description clearly describes the changes included in the pull request.
- [ ] Any category I am creating has the minimum requirement of 3 items

### CODE REVIEW

**Comment by vaibh27** [comment]
Hi @gdjohn4s,
Could you please review the PR for the following issue
https://github.com/Exifly/ApiVault/issues/266

Thanks

**Review by gdjohn4s — APPROVED** [review]
Approved.
Waiting for @FlavioAdamo to merge

**Comment by vaibh27** [comment]
Thanks, @gdjohn4s 

Let me know If there are any other issues to pick.

**Review by FlavioAdamo — APPROVED** [review]

**Comment by FlavioAdamo** [comment]
Approved!

**Pull request merged**
