### PR TITLE
Added border gradient animation to search bar

### PR DESCRIPTION
**Pull request by gianmazzoran**
https://github.com/Exifly/ApiVault/assets/16735648/a8e3a4c3-1391-43a8-9f2f-34b8cda5756c

#142

### CODE REVIEW

**Comment by FlavioAdamo** [comment]
@gianmazzoran  Super cool! You've done a really good job with the implementation. Do you think it's possible to make the animation appear only when you click on the searchabr?

**Comment by gianmazzoran** [comment]
@FlavioAdamo thanks! Yeah, ill update the PR with the animation when is focused

**Comment by gianmazzoran** [comment]
@FlavioAdamo I've updated the PR

https://github.com/Exifly/ApiVault/assets/16735648/c6d11768-4ad7-45b7-a94e-89c56e2cac32

**Comment by FlavioAdamo** [comment]
@gianmazzoran I like it!
@gdjohn4s what do you think?

**Comment by gdjohn4s** [comment]
@FlavioAdamo approved! 🙂

**Review by FlavioAdamo — APPROVED** [review]

**Comment by FlavioAdamo** [comment]
Pull request accepted!

**Pull request merged**
