### PR TITLE
Update README.md

### LINKED ISSUE #49: Updated the README.md
Hey! I really liked the idea and this project.
I am currently a beginner to web development and make non-code contributions on GitHub.

Changes made:
+ Added a H1 to the top for more impact
+ Added emojis to subheadings
+ Added cool badges for frameworks
+ Improved the contributing section
+ Improved the support section
+ Improved the LICENSE Section

Do let me know if the PR is accepted or if I have to make some changes

Regards!!!

### PR DESCRIPTION
**Pull request by the-amazing-atharva**
fixes #49 

More info in issue linked above ie #49

### CODE REVIEW

**Comment by gdjohn4s** [comment]
Thank you for contributing!

I really like how you structured the README.md. 
I am adding @FlavioAdamo for approval as well.

**Review by gdjohn4s — APPROVED** [review]
I like it.
Review passed ✅

**Comment by FlavioAdamo** [comment]
I love it!!

**Comment by the-amazing-atharva** [comment]
Thanks for the comments guys @gdjohn4s @FlavioAdamo !!!

**Pull request merged**
